### ISSUE TITLE
unsupported operand type(s) for -: 'datetime.datetime' and 'str'

### ISSUE THREAD

**Issue by rosdyana** [celery/django-celery-results#104]
Recently I got this on my django app logs.

Task celery.backend_cleanup with id f516a28c-58b8-415d-8389-ef9d4dc2722a raised exception:
TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'str'")

Task was called with args: [] kwargs: {}.

The contents of the full traceback was:

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/celery/app/builtins.py", line 25, in backend_cleanup
    app.backend.cleanup()
  File "/app/.heroku/python/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 71, in cleanup
    self.TaskModel._default_manager.delete_expired(self.expires)
  File "/app/.heroku/python/lib/python3.7/site-packages/django_celery_results/managers.py", line 167, in delete_expired
    self.get_all_expired(expires).update(hidden=True)
  File "/app/.heroku/python/lib/python3.7/site-packages/django_celery_results/managers.py", line 162, in get_all_expired
    return self.filter(date_done__lt=now() - maybe_timedelta(expires))
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'
```

django version 2.2
django celery results version 1.1.2
celery version 4.1.1

**Comment by rosdyana** [comment]
@auvipy any reason why this issue has been closed? at least give some suggestions, or the logs not complete, or need something else to support it?

**Comment by rosdyana** [comment]
Figured out the issue was celery result expires set in string type, should be int. sorry my bad.
