### ISSUE TITLE
_mysql_connector.MySQLInterfaceError: Column 'hidden' cannot be null

### ISSUE THREAD

**Issue by jmartens** [celery/django-celery-results#109]
When trying to run a task inside my Django project I get the following traceback each time a task is ran:

```
[2019-08-10 18:16:00,663: ERROR/MainProcess] Pool callback raised exception: AttributeError("'NoneType' object has no attribute 'strip'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 472, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Column 'hidden' cannot be null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/django/base.py", line 168, in _execute_wrapper
    return method(query, args)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 475, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'hidden' cannot be null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/django/base.py", line 218, in execute
    return self._execute_wrapper(self.cursor.execute, query, new_args)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/django/base.py", line 174, in _execute_wrapper
    utils.IntegrityError(err.msg), sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line 683, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/django/base.py", line 168, in _execute_wrapper
    return method(query, args)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 475, in cmd_query
    sqlstate=exc.sqlstate)
django.db.utils.IntegrityError: Column 'hidden' cannot be null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 606, in statement
    return self._executed.strip().decode('utf8')
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1750, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/request.py", line 371, in on_failure
    store_result=self.store_errors,
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 160, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 342, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 38, in _store_result
    using=using,
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/managers.py", line 133, in store_result
    obj.save(using=using)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/django/operations.py", line 127, in last_executed_query
    return force_text(cursor.statement, errors='replace')
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/django/base.py", line 230, in __getattr__
    return getattr(self.cursor, attr)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 608, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

I traced it back to the django_celery_results_taskresult table:
```
MariaDB [(none)]>  SELECT DISTINCT TABLE_NAME
    ->      FROM INFORMATION_SCHEMA.COLUMNS
    ->      WHERE TABLE_SCHEMA='app' AND COLUMN_NAME='hidden'\G
*************************** 1. row ***************************
TABLE_NAME: django_celery_results_taskresult
1 row in set (0.001 sec)
```

I am using:
celery==4.3.0
Django==2.2.4
django-celery-beat==1.5.0
django-celery-results==1.1.2
mysql-connector-python==8.0.17

with 10.4.7-MariaDB-1:10.4.7+maria~bionic in docker container

**Comment by auvipy** [comment]
i hope its fixed in latest release
