### ISSUE TITLE
AppRegistryNotReady - apps aren't loaded yet

### ISSUE THREAD

**Issue by grantmcconnaughey** [celery/django-celery-results#11]
I receive an `AppRegistryNotReady` exception when starting up the celery worker using `celery worker -A myapp.celery`. I am the following versions:

```
django-celery-results (1.0.1)
celery (4.0.2)
```

My `CELERY_RESULT_BACKEND` is `'django-db'`.`django_celery_results` is in `INSTALLED_APPS`.

I understand why this is happening... I'm not starting up Celery in the context of a `manage.py` script. But I'm wondering how I'm supposed to start celery if I'm using the DB backend with django-celery-results.

How should I be starting up the celery worker using django-celery-results?

The full traceback:

```
[2016-12-21 21:56:51,028: CRITICAL/MainProcess] Unrecoverable error: AppRegistryNotReady("Apps aren't loaded yet.",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 158, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 221, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 1182, in backend
    return self._get_backend()
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 900, in _get_backend
    self.loader)
  File "/usr/local/lib/python2.7/site-packages/celery/app/backends.py", line 65, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python2.7/site-packages/celery/app/backends.py", line 45, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/django_celery_results/backends/__init__.py", line 4, in <module>
    from .database import DatabaseBackend
  File "/usr/local/lib/python2.7/site-packages/django_celery_results/backends/database.py", line 7, in <module>
    from ..models import TaskResult
  File "/usr/local/lib/python2.7/site-packages/django_celery_results/models.py", line 17, in <module>
    class TaskResult(models.Model):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by mheppner** [comment]
What does your `celery.py` file look like? Since `djcelery` has gone away, you'll never be starting Celery through `manage.py` anymore. Instead, you start it directly from the `celery` command. For this to work though, Django will have to be initialized, which means you need the `DJANGO_SETTINGS_MODULE` environment variable.

Your `celery.py` file should contain this at the top, before you create your `app`:
```
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')
```

**Comment by grantmcconnaughey** [comment]
My project structure looks like this:

```
myapp
├── __init__.py
├── celery.py
├── apps/
│   ├── app1/
│   ├── app2/
```

### `celery.py`

```
from __future__ import absolute_import
import os

from celery import Celery
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myapp.settings')

app = Celery('myapp')

CELERY_TIMEZONE = 'UTC'

app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```

### `__init__.py`

```
from __future__ import absolute_import

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app  # noqa
```

**Comment by grantmcconnaughey** [comment]
Now I'm starting to wonder if my worker Docker container didn't get its dependencies updated and is still on celery 3.x... let me double check that real quick.

**Comment by grantmcconnaughey** [comment]
Ugh, I never updated the worker's dependencies, so Celery was still on version 3. Mea culpa.

**Comment by mheppner** [comment]
FYI I don't think Celery reads constants in `celery.py` (looking at your `CELERY_TIMEZONE` above). The line after that is where it's getting the config, which is from your settings file. In your settings, you can just set it to the Django time zone, `CELERY_TIMEZONE = TIME_ZONE`. Also, with Celery 4, you don't need to have the lambda in the `autodiscover_tasks()`, it knows how to properly use the Django apps.

**Comment by grantmcconnaughey** [comment]
All good info, @mheppner. Thanks!
