### ISSUE TITLE
"permission denied for schema public" after doing initial migrate

### ISSUE THREAD

**Issue by sakoht** [celery/django-celery-results#126]
I've been using celery w/o a backend, and have just attempted to add django-celery-results.

The instructions here are clear, but when I do the migrate I get an error _afterward_, and it is unclear to me if/how this affects things:

Thanks if you have any insight:
```
> ./manage.py migrate django_celery_results
settings: enkodjango.settings.local
Operations to perform:
  Apply all migrations: django_celery_results
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 1: SELECT 1 FROM ONLY "public"."django_content_type" x WHERE "i...
                           ^
QUERY:  SELECT 1 FROM ONLY "public"."django_content_type" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/migrate.py", line 257, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/management/__init__.py", line 83, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 480, in bulk_create
    obj_without_pk._state.db = self.db
  File "/usr/local/lib/python3.6/dist-packages/django/db/transaction.py", line 240, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
django.db.utils.ProgrammingError: permission denied for schema public
LINE 1: SELECT 1 FROM ONLY "public"."django_content_type" x WHERE "i...
                           ^
QUERY:  SELECT 1 FROM ONLY "public"."django_content_type" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x
```

**Comment by auvipy** [comment]
sorry, this seems to be a problem with your DB, not this package. but feel free to prove this is.
