### ISSUE TITLE
InterfaceError in store_result in celery.app.trace.handle_failure

### ISSUE THREAD

**Issue by DylanYoung** [celery/django-celery-results#137]
I believe this was triggered by running a too-small pgbouncer pool in front of celery, but could be unrelated. 

Using gevent workers
django-celery-results==1.0.1
gevent 1.4
celery 4.2.2

Anyone else seen this one? 

Traceback 
------------

```
[2020-02-28 10:09:31,745: WARNING/celerybw/MainProcess] Traceback (most recent call last):
[2020-02-28 10:09:31,751: WARNING/celerybw/MainProcess] File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2020-02-28 10:09:31,751: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/concurrency/base.py", line 31, in apply_target
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] ret = target(*args, **kwargs)
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/app/trace.py", line 549, in _fast_trace_task
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] uuid, args, kwargs, request,
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/app/trace.py", line 492, in trace_task
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] I, _, _, _ = on_error(task_request, exc, uuid)
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/app/trace.py", line 338, in on_error
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] task, request, eager=eager, call_errbacks=call_errbacks,
[2020-02-28 10:09:31,752: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/app/trace.py", line 172, in handle_error_state
[2020-02-28 10:09:31,753: WARNING/celerybw/MainProcess] call_errbacks=call_errbacks)
[2020-02-28 10:09:31,753: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/app/trace.py", line 217, in handle_failure
[2020-02-28 10:09:31,753: WARNING/celerybw/MainProcess] call_errbacks=call_errbacks,
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/backends/base.py", line 157, in mark_as_failure
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] traceback=traceback, request=request)
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/celery/backends/base.py", line 322, in store_result
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] request=request, **kwargs)
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django_celery_results/backends/database.py", line 29, in _store_result
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] meta=meta,
[2020-02-28 10:09:31,754: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django_celery_results/managers.py", line 50, in _inner
[2020-02-28 10:09:31,755: WARNING/celerybw/MainProcess] return fun(*args, **kwargs)
[2020-02-28 10:09:31,755: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django_celery_results/managers.py", line 119, in store_result
[2020-02-28 10:09:31,761: WARNING/celerybw/MainProcess] obj, created = self.get_or_create(task_id=task_id, defaults=fields)
[2020-02-28 10:09:31,761: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
[2020-02-28 10:09:31,763: WARNING/celerybw/MainProcess] return getattr(self.get_queryset(), name)(*args, **kwargs)
[2020-02-28 10:09:31,763: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/query.py", line 465, in get_or_create
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] return self.get(**lookup), False
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] num = len(clone)
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] self._fetch_all()
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] self._result_cache = list(self.iterator())
[2020-02-28 10:09:31,764: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
[2020-02-28 10:09:31,765: WARNING/celerybw/MainProcess] results = compiler.execute_sql()
[2020-02-28 10:09:31,765: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
[2020-02-28 10:09:31,765: WARNING/celerybw/MainProcess] cursor = self.connection.cursor()
[2020-02-28 10:09:31,769: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 233, in cursor
[2020-02-28 10:09:31,769: WARNING/celerybw/MainProcess] cursor = self.make_cursor(self._cursor())
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 206, in _cursor
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] return self.create_cursor()
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] six.reraise(dj_exc_type, dj_exc_value, traceback)
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 206, in _cursor
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] return self.create_cursor()
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] File "/home/www/env/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 210, in create_cursor
[2020-02-28 10:09:31,770: WARNING/celerybw/MainProcess] cursor = self.connection.cursor()
[2020-02-28 10:09:31,771: WARNING/celerybw/MainProcess] InterfaceError: connection already closed
```

**Comment by auvipy** [comment]
update to the latest versions and report again.
