### ISSUE TITLE
Support for mongodb with djongo

### ISSUE THREAD

**Issue by SandoDev** [celery/django-celery-results#155]
I am trying to use mongodb with the [djongo](https://nesdis.github.io/djongo/) package and I would also like to use django_celery_results but when I run migrations it causes a problem for me.

My requiremets
```
bson==0.5.8
dataclasses==0.6
Django==2.2.12
djongo==1.3.1
pymongo==3.10.1
python-dateutil==2.8.1
pytz==2019.3
six==1.14.0
sqlparse==0.2.4

djangorestframework==3.11.1
drf-yasg==1.17.1
littlenv==0.1.7
celery==4.4.0
django-celery-results==1.2.0
```
The error:
```
python manage.py migrate       
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, django_celery_results, sessions
Running migrations:
Applying django_celery_results.0006_taskresult_date_created...Traceback (most recent call last):
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 824, in parse
    return handler(self, statement)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 953, in _update
    self._query = UpdateQuery(self.db, self.connection_properties, sm, self._params)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 309, in __init__
    super().__init__(*args)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 72, in __init__
    self.parse()
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 339, in parse
    kwargs.update(self.set_columns.to_mongo())
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/converters.py", line 351, in to_mongo
    for sql in self.sql_tokens}
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/converters.py", line 351, in <dictcomp>
    for sql in self.sql_tokens}
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/__init__.py", line 200, in rhs_indexes
    raise SQLDecodeError
djongo.sql2mongo.SQLDecodeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django_celery_results/migrations/0006_taskresult_date_created.py", line 17, in copy_date_done_to_date_created
    date_created=models.F('date_done')
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/models/query.py", line 741, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 753, in __init__
    self.parse()
  File "/home/camilo/ZProjects/interview/venv/lib/python3.6/site-packages/djongo/sql2mongo/query.py", line 846, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: UPDATE "django_celery_results_taskresult" SET "date_created" = "django_celery_results_taskresult"."date_done"
Params: ()
Version: 1.3.1
```
The error is with migration 6 and I don't know if with 7
![Selection_047](https://user-images.githubusercontent.com/46248182/90840638-20626780-e320-11ea-8269-de99a089eef9.png)

**Comment by auvipy** [comment]
out of the scope of this package

**Comment by P-Sood** [comment]
Any idea on when this will be fixed/added?

**Comment by auvipy** [comment]
this is not an issue of this library actually. need fund + contribution

**Comment by SandoDev** [comment]
@auvipy thanks for the clarification

**Comment by devanshpatel13** [comment]
@auvipy, i tried many possible solution but still i faced that same error when fire migrate command. so please give me solution

**Comment by prathamvs** [comment]
So did you get any solution for this??

**Comment by SathyaSomasundaram** [comment]
Did anyone solved the issue.? or any work around .?
