### ISSUE TITLE
Integration with djongo package

### ISSUE THREAD

**Issue by aceaceace30** [celery/django-celery-results#170]
Good Day, I was using [djongo](https://github.com/nesdis/djongo) package in my application because we mainly use mongodb for our database but I am having issue when trying to run migrate. Here is the traceback for reference:

`Traceback (most recent call last):
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\djongo\cursor.py", line 56, in execute
    params)
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\djongo\sql2mongo\query.py", line 769, in __init__
    self._query = self.parse()
  File "C:\Users\Ababao\Projects\valens\pwc-benchmarking\venv\lib\site-packages\djongo\sql2mongo\query.py", line 864, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError: FAILED SQL: UPDATE "django_celery_results_taskresult" SET "date_created" = "django_celery_results_taskresult"."date_done"
Params: ()
Version: 1.3.2
`

Hope this could be addressed. Thank you so much devs.

**Comment by auvipy** [comment]
this is out of the scope of this package. you need to work on it of your own

**Comment by ExaltedA** [comment]
@aceaceace30 Hello, I wonder If you solved this issue?
