### ISSUE TITLE
Module celery.five not found

### ISSUE THREAD

**Issue by Koen1999** [celery/django-celery-results#174]
I am getting the following error strack:
```
Traceback (most recent call last):
  File "./djangosite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/django_celery_results/models.py", line 9, in <module>
    from celery.five import python_2_unicode_compatible
ModuleNotFoundError: No module named 'celery.five'
```

I am using `Python 3.6.9` with the following (relevant) pip packages and versions:
```
amqp==5.0.2
buildtools==1.0.6
celery==5.0.2
Django==3.1.3
django-celery-beat==2.1.0
django-celery-results==1.2.1
django-common-helpers==0.9.2
django-timezone-field==4.0
uWSGI==2.0.19.1
```

It may be related to this: https://github.com/celery/celery/pull/6338

**Comment by arnau126** [comment]
Duplicated #157
