### ISSUE TITLE
After upgrading to versionn 2.0.0 exception is thrown when trying to access existing AsyncResults

### ISSUE THREAD

**Issue by BITSOLVER** [celery/django-celery-results#176]
After upgrading to version 2.0.0 (Celery 5.0.x) the following exception is thrown for results that are all ready in the database:

Traceback (most recent call last):
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/utils/json.py", line 88, in loads
    return stdjson.loads(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/auth_ext/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/task_ext/views/task_ext.py", line 109, in dispatch
    return super(AjaxTaskManagerView, self).dispatch(request, *args, *kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/auth_ext/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/bookings_manager_utils/views/base.py", line 515, in dispatch
    return super(BaseActionsDatatableView, self).dispatch(request, *args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/bookings_manager_utils/views/base.py", line 232, in dispatch
    return super(SecureDatatableView, self).dispatch(request, *args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/bookings_manager_utils/views/base.py", line 118, in get
    return BaseDatatableView.get(self, request, *args, **kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_datatables_view/mixins.py", line 50, in get
    func_val = self.get_context_data(**kwargs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_datatables_view/base_datatable_view.py", line 373, in get_context_data
    return self.handle_exception(e)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_datatables_view/base_datatable_view.py", line 310, in handle_exception
    raise e
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_datatables_view/base_datatable_view.py", line 364, in get_context_data
    data = self.prepare_results(qs)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_datatables_view/base_datatable_view.py", line 301, in prepare_results
    data.append([self.render_column(item, column) for column in self._columns])
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_datatables_view/base_datatable_view.py", line 301, in <listcomp>
    data.append([self.render_column(item, column) for column in self._columns])
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/task_ext/views/task_ext.py", line 115, in render_column
    return super(AjaxTaskManagerView, self).render_column(row, column)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/bookings_manager_utils/views/base.py", line 519, in render_column
    return self.render_actions(row)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/task_ext/views/task_ext.py", line 119, in render_actions
    async_result = self.model.objects.get_task_state(row.task_name, row.task_key)
  File "/Users/steven/PycharmProjects/bookingsmanager/BookingsManager/src/task_ext/models/task_ext.py", line 107, in get_task_state
    logger.info("Task state: %s" % async_result.state)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/result.py", line 477, in state
    return self._get_task_meta()['status']
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/result.py", line 416, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/backends/base.py", line 519, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 62, in _get_task_meta_for
    task_args = self.decode_content(obj, res.get('task_args'))
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 80, in decode_content
    return self.decode(content)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/backends/base.py", line 349, in decode
    accept=self.accept)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 53, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/utils/json.py", line 88, in loads
    return stdjson.loads(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
kombu.exceptions.DecodeError: Expecting value: line 1 column 1 (char 0)

This can be fixed by running the following to surround args and kwargs in double quotes with:

```python
        from logging import getLogger
        from django_celery_results.models import TaskResult
        from django.db.models import Value
        from django.db.models.functions import Concat
        results = TaskResult.objects.filter(task_args__isnull=False).exclude(task_args__contains='"').update(
            task_args=Concat(Value('"'), 'task_args', Value('"'))
        )
        logger.info(f"Upated {results} args.")
        results = TaskResult.objects.filter(task_kwargs__isnull=False).exclude(task_kwargs__contains='"').update(
            task_kwargs=Concat(Value('"'), 'task_kwargs', Value('"'))
        )
        logger.info(f"Upated {results} kwargs.")
```

Is this the correct way to fix the issue, and if it is then this needs to be added to a new migration file.

**Comment by auvipy** [comment]
can not be sure from the trackback about the issue. can you share the trackback properly?

**Comment by BITSOLVER** [comment]
When I look at the database table with results created prior to 2.0.0 the columns for task_args and task_kwargs look like:

| task_args | task_kwargs |
| --- | --- |
| () | {'task_key': '10', 'repeat': 16, 'delay': 1} |

If I upgrade and try and inspect the result I can the error mentioned above, but if I clear the table and run the task again it populates like this:

| task_args | task_kwargs |
| --- | --- |
| "()" | "{'task_key': '10', 'repeat': 16, 'delay': 1}" |

It seems that the JSon value needs wrapping in double quotes.

In a Python console I can get the error just by trying in inspect the state:

```python
rs = task_ext_demo.AsyncResult(task_id="72caa104-bd64-4f51-b9dd-5e32e0a67dd6")
rs.state
Traceback (most recent call last):
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/utils/json.py", line 88, in loads
    return stdjson.loads(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/result.py", line 477, in state
    return self._get_task_meta()['status']
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/result.py", line 416, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/backends/base.py", line 519, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 62, in _get_task_meta_for
    task_args = self.decode_content(obj, res.get('task_args'))
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 80, in decode_content
    return self.decode(content)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/celery/backends/base.py", line 349, in decode
    accept=self.accept)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 53, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 49, in _reraise_errors
    yield
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/serialization.py", line 262, in loads
    return decode(data)
  File "/Users/steven/.virtualenvs/bookingsmanager-3.6/lib/python3.6/site-packages/kombu/utils/json.py", line 88, in loads
    return stdjson.loads(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
kombu.exceptions.DecodeError: Expecting value: line 1 column 1 (char 0)
```

This seems to affect most properties of the AsyncResult, as in screen shot from debugger.
![Screenshot 2020-11-30 at 14 41 08](https://user-images.githubusercontent.com/15092505/100623646-57cab200-331a-11eb-8525-01940d6ccb13.png)

**Comment by auvipy** [comment]
can you please try this patch https://github.com/celery/django-celery-results/pull/178?
