### ISSUE TITLE
Celery workers generating the following exception when task is revoked.

### ISSUE THREAD

**Issue by ngrj93** [celery/django-celery-results#183]
`[2021-01-16` 10:34:39,168: ERROR/MainProcess] Pool callback raised exception: DoesNotExist('ChordCounter matching query does not exist.')
Traceback (most recent call last):
  File "/lib/python38/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/lib/python3.8/site-packages/celery/worker/request.py", line 531, in on_failure
    self.task.backend.mark_as_failure(
  File "/lib/python3.8/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    self.on_chord_part_return(request, state, exc)
  File "/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 112, in on_chord_part_return
    ChordCounter.objects.select_for_update()
  File "/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist.`

When a task (chain of groups) is revoked, I see the following exception being generated in the workers.

Issue https://github.com/celery/django-celery-results/issues/177 seems to be related.

**Comment by ngrj93** [comment]
^ Issue was caused due to atomic_requests being enabled and time taken by view exceeding async task return time.
