### ISSUE TITLE
<id>/group/status/ is broken

### ISSUE THREAD

**Issue by insspb** [celery/django-celery-results#214]
It seems that this part of code was not tested at all.

Error:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/site-packages/django_celery_results/views.py", line 49, in group_status
    retval = result.result
```

Possible reason (will not test, will remove current master as very dirty), but:

https://github.com/celery/django-celery-results/blob/3ddad5b72eeda38de8738cc6cc13f54571cc87ae/django_celery_results/views.py#L49

Not clear what expected to receive as no documentation for this part, but probably it should be
```
retval = result.results
```

With additional `s`, as it is group.

**Comment by auvipy** [comment]
@AlecTroemel

**Comment by AlecTroemel** [comment]
from the celery docs, sound like you're right https://docs.celeryproject.org/en/latest/reference/celery.result.html?highlight=GroupResult#celery.result.GroupResult.results

it should be something `retval = result.results`

I'll try and get a fix+test in a MR asap
