### ISSUE TITLE
'DatabaseBackend' object has no attribute '_encode' when CELERY_RESULT_BACKEND = 'django-db'

### ISSUE THREAD

**Issue by William1Wu** [celery/django-celery-results#233]
Hi All,

I am trying to use django-celery-results to store task status to backend database.
Following is my environment packages and settings. 

```
Windows 10
Python: 3.6.13
Django: 3.0.8
celery: 3.1.24
django-celery-results: 1.0.0
flower: 0.9.1
RabbitMQ: 3.9.5
```

**Setting.py**
`CELERY_RESULT_BACKEND = 'django-db'`

**Celery.py**
`app.loader.override_backends['django-db'] = 'django_celery_results.backends.database:DatabaseBackend'`

I add a function named sleep as shared_task and Celery works fine.
But it get an error **AttributeError: 'DatabaseBackend' object has no attribute '_encode**
when task is done and celery is trying to store task status to database. 
However, I can't find any private function named self._encode in /django_celery_results/backends/database.py
Does anyone get this error? Thanks.

Here is error log:

```
[2021-09-13 11:48:09,746: CRITICAL/MainProcess] Task buildinstaller.tasks.sleep[44f1857a-c254-412e-b662-3c581fab8f2f] INTERNAL ERROR: AttributeError("'DatabaseBackend' object has no attribute '_encode'",)
Traceback (most recent call last):
  File "d:\software\anaconda3\envs\django_buildinstaller\lib\site-packages\celery\app\trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "d:\software\anaconda3\envs\django_buildinstaller\lib\site-packages\celery\backends\base.py", line 271, in store_result
    request=request, **kwargs)
  File "d:\software\anaconda3\envs\django_buildinstaller\lib\site-packages\django_celery_results\backends\database.py", line 21, in _store_result
    content_type, content_encoding, result = self.encode_content(result)
  File "d:\software\anaconda3\envs\django_buildinstaller\lib\site-packages\django_celery_results\backends\database.py", line 46, in encode_content
    content_type, content_encoding, content = self._encode(data)
**AttributeError: 'DatabaseBackend' object has no attribute '_encode'**
```

**Comment by auvipy** [comment]
you are using unsupported versions. use pip install -U package name

**Comment by William1Wu** [comment]
@auvipy Thanks for reply. I find the root cause.
self._encode() is defined in celery\backends\base.py after version 4.0.0. 
But I used version 3.1.24 ... So my workaround is to self-define self._encode(). It seems work fine.

**Comment by auvipy** [comment]
celery 4.4.6 should work on windows, we reintroduced that support
