### ISSUE TITLE
.delay() caused "Duplicate entry '1' for key 'PRIMARY"

### ISSUE THREAD

**Issue by Zoom2016** [celery/django-celery-results#237]
**Package version:**
django-celery-results==2.0.0
celery==5.0.5
SQLAlchemy==1.4.4

**Middleware**
Broker: MySQL
Backend: MySQL

**Description**
Occasionally, when I check.delay() to create an asynchronous task, an error has occurred. It looks like the primary key ID inserted into the database is duplicate. I can't continue until I clear the kombu_message table. Here are the details

[2021-09-23 16:48:51] [ERROR] [/usr/local/archeros-lcm2/server/apps/common/rest_framework/exception.py/exception.py:227 -> custom_exception_handler] Http 500 error::
Traceback (most recent call last):
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/archeros-lcm2/server/apps/deploy/views.py", line 98, in create
    result = celery_run_cmd.delay(task_info=task_cmd_manager, step=step, host_list=host_list,
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/celery/app/task.py", line 421, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/celery/app/task.py", line 561, in apply_async
    return app.send_task(
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/celery/app/base.py", line 749, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/celery/app/amqp.py", line 523, in send_task_message
    ret = producer.publish(
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/kombu/messaging.py", line 175, in publish
    return _publish(
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/kombu/connection.py", line 525, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/kombu/messaging.py", line 197, in _publish
    return channel.basic_publish(
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
    return self._put(routing_key, message, **kwargs)
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 103, in _put
    obj = self._get_or_create(queue)
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/kombu/transport/sqlalchemy/__init__.py", line 79, in _get_or_create
    obj = self.session.query(self.queue_cls) \
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2716, in first
    return self.limit(1)._iter().first()
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2800, in _iter
    result = self.session.execute(
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1661, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1511, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/usr/local/archeros-lcm2/pyvenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1' for key 'PRIMARY'")
[SQL: INSERT INTO kombu_message (id, visible, timestamp, payload, version, queue_id) VALUES (%(id)s, %(visible)s, %(timestamp)s, %(payload)s, %(version)s, %(queue_id)s)]
[parameters: {'id': 1, 'visible': 1, 'timestamp': None, 'payload': '{"body": "W1tdLCB7InRhc2tfaW5mbyI6IHsicGF0aCI6ICIvdXNyL2xvY2FsL2FyY2hlcm9zLWxjbV9saWJzL2h5Q2xvdWRPcyIsICJjbWQiOiAiYW5zaWJsZS1wbGF5Ym9vayAtaSB0ZW1wb3J ... (18144 characters truncated) ... _info": {"exchange": "", "routing_key": "celery"}, "priority": 0, "body_encoding": "base64", "delivery_tag": "77b083cf-cd60-4b5d-9042-fa3c307a8d92"}}', 'version': 1, 'queue_id': 1}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

**Comment by auvipy** [comment]
try 2.2 and report again
