### ISSUE TITLE
Null task_id on failure

### ISSUE THREAD

**Issue by daveisfera** [celery/django-celery-results#241]
This is happening in our development environment and I haven't been able to make a simple reproducer for the error yet, but here's what we're seeing:
```
/usr/local/lib/python3.7/site-packages/celery/app/trace.py:661: RuntimeWarning: Exception raised outside body: IntegrityError('null value in column "task_id" violates not-null constraint\nDETAIL:  Failing row contains (192684, null, FAILURE, application/json, utf-8, {"exc_type": "ChordError", "exc_message": ["MultipleObjectsRetur..., 2021-10-04 17:43:28.490971+00, Traceback (most recent call last):\n  File "/usr/local/lib/python..., {"children": [[["279fc555-d02a-42bc-b6ad-b410314b1ac2", null], n..., null, null, null, null, 2021-10-04 17:43:28.490953+00).\n'):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 223, in trigger_callback
    ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 749, in join
    disable_sync_subtasks=disable_sync_subtasks,
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 219, in get
    self.maybe_throw(callback=callback)
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 335, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/usr/local/lib/python3.7/site-packages/celery/result.py", line 328, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vine/promises.py", line 234, in throw
    reraise(type(exc), exc, tb)
  File "/usr/local/lib/python3.7/site-packages/vine/utils.py", line 30, in reraise
    raise value
game.models.flow.Appearance.MultipleObjectsReturned: get() returned more than one Appearance -- it returned 2!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/database_psycopg2.py", line 65, in execute
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/database_dbapi2.py", line 38, in execute
    *args, **kwargs)
psycopg2.errors.NotNullViolation: null value in column "task_id" violates not-null constraint
DETAIL:  Failing row contains (192684, null, FAILURE, application/json, utf-8, {"exc_type": "ChordError", "exc_message": ["MultipleObjectsRetur..., 2021-10-04 17:43:28.490971+00, Traceback (most recent call last):
  File "/usr/local/lib/python..., {"children": [[["279fc555-d02a-42bc-b6ad-b410314b1ac2", null], n..., null, null, null, null, 2021-10-04 17:43:28.490953+00).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 518, in trace_task
    uuid, retval, task_request, publish_result,
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 163, in mark_as_done
    self.on_chord_part_return(request, state, result)
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 208, in on_chord_part_return
    group_result=deps
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 231, in trigger_callback
    app.backend.chord_error_from_stack(callback, ChordError(reason))
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 302, in chord_error_from_stack
    return backend.fail_from_current_stack(callback.id, exc=exc)
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 309, in fail_from_current_stack
    self.mark_as_failure(task_id, exc, exception_info.traceback)
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 172, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/local/lib/python3.7/site-packages/celery/backends/base.py", line 483, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 78, in _store_result
    using=using,
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/managers.py", line 46, in _inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/managers.py", line 169, in store_result
    defaults=fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 541, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 583, in _create_object_from_params
    raise e
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 782, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 911, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/database_psycopg2.py", line 65, in execute
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/database_dbapi2.py", line 38, in execute
    *args, **kwargs)
django.db.utils.IntegrityError: null value in column "task_id" violates not-null constraint
DETAIL:  Failing row contains (192684, null, FAILURE, application/json, utf-8, {"exc_type": "ChordError", "exc_message": ["MultipleObjectsRetur..., 2021-10-04 17:43:28.490971+00, Traceback (most recent call last):
  File "/usr/local/lib/python..., {"children": [[["279fc555-d02a-42bc-b6ad-b410314b1ac2", null], n..., null, null, null, null, 2021-10-04 17:43:28.490953+00).


  exc, exc_info.traceback)))
```

**Comment by auvipy** [comment]
this seems to be an issue of your code or the packages you are using. task_id can't be null

**Comment by auvipy** [comment]
you can check the code of the package first to figure out if any error in code
