### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by yanshicheng** [celery/django-celery-results#306]
Psycopg2 is not used in the project，
Why is the error reported?
Must I use psycopg2？
MySQL for Django storage

(pgoops) root@code_project pgoops %  celery -A pgoops worker -l info -n pgoops_celery_worker@%h
[2022-04-20 00:55:53,301: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'psycopg2'")
Traceback (most recent call last):
  File "...lib/python3.10/site-packages/celery/app/base.py", line 1250, in backend
    return self._local.backend
AttributeError: '_thread._local' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File ".../lib/python3.10/site-packages/celery/bootsteps.py", line 112, in start
    self.on_start()
  File ".../lib/python3.10/site-packages/celery/apps/worker.py", line 136, in on_start
    self.emit_banner()
  File ".../lib/python3.10/site-packages/celery/apps/worker.py", line 170, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File ".../lib/python3.10/site-packages/celery/apps/worker.py", line 232, in startup_info
    results=self.app.backend.as_uri(),
  File ".../lib/python3.10/site-packages/celery/app/base.py", line 1252, in backend
    self._local.backend = new_backend = self._get_backend()
  File ".../lib/python3.10/site-packages/celery/app/base.py", line 955, in _get_backend
    backend, url = backends.by_url(
  File ".../lib/python3.10/site-packages/celery/app/backends.py", line 69, in by_url
    return by_name(backend, loader), url
  File ".../lib/python3.10/site-packages/celery/app/backends.py", line 49, in by_name
    cls = symbol_by_name(backend, aliases)
  File ".../lib/python3.10/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File ".../lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "...lib/python3.10/site-packages/django_celery_results/backends/__init__.py", line 2, in <module>
    from .database import DatabaseBackend
  File "...lib/python3.10/site-packages/django_celery_results/backends/database.py", line 13, in <module>
    from psycopg2 import InterfaceError as Psycopg2InterfaceError
ModuleNotFoundError: No module named 'psycopg2'

**Comment by auvipy** [comment]
are you using latest https://github.com/celery/django-celery-results/releases/tag/v2.3.1 ?

**Comment by yanshicheng** [comment]
thank you My is v2.3.0
