### ISSUE TITLE
chords throwing django.db.utils.NotSupportedError: LIMIT/OFFSET is not supported with select_for_update

### ISSUE THREAD

**Issue by zenoran** [celery/django-celery-results#308]
Django version:  2.2.28
Celery version: 5.2.3
Python version: 3.9.10
django-celery-results version: 2.3.1

Starting to see this issue as part of upgrading to a newer celery running on Oracle 12c.  Group tasks are failing with the following trace:

`django.db.utils.NotSupportedError: LIMIT/OFFSET is not supported with select_for_update on this database backend.
[2022-04-27 19:38:40,730: ERROR/MainProcess] Pool callback raised exception: NotSupportedError('LIMIT/OFFSET is not supported with select_for_update on this database backend.')
Traceback (most recent call last):
  File "/python3.9/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/python3.9/site-packages/celery/worker/request.py", line 577, in on_failure
    self.task.backend.mark_as_failure(
  File "/python3.9/site-packages/celery/backends/base.py", line 177, in mark_as_failure
    self.on_chord_part_return(request, state, exc)
  File "/python3.9/site-packages/django_celery_results/backends/database.py", line 221, in on_chord_part_return
    ChordCounter.objects.select_for_update()
  File "/python3.9/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/python3.9/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/python3.9/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/python3.9/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/python3.9/site-packages/django/db/models/sql/compiler.py", line 1129, in execute_sql
    sql, params = self.as_sql()
  File "/python3.9/site-packages/django/db/models/sql/compiler.py", line 521, in as_sql
    raise NotSupportedError(
django.db.utils.NotSupportedError: LIMIT/OFFSET is not supported with select_for_update on this database backend.`

I think the error is self-explanatory, but I'm not quite sure why we're just starting to see this now with a newer version of celery.  I wanted to at least get this post out before I start digging deeper to see if anyone in the community had any advice on how to avoid this without hacking the code.

BTW... triggering code is something like this example from celery documentation:

`res = (add.s(4, 4) | group(add.si(i, i) for i in range(10)))()`

`

**Comment by auvipy** [comment]
it's probably django issue

**Comment by zenoran** [comment]
> it's probably django issue

I believe it's a bug introduced by this commit:
https://github.com/celery/django-celery-results/commit/3f74b825fc1d7af6d5dccc9a9ff583abfb0aa0ab

The django documentation states select_for_update would lock all rows in the queryset, but by adding the first() function on the filter it's trying to do something against design?  Are you suggesting Django should raise an error when trying to combine first() with a filtered select_for_update() queryset??  That still wouldn't address the bug in this library, though?

**Comment by auvipy** [comment]
mmm , can you come with a proposed solution?

**Comment by zenoran** [comment]
> mmm , can you come with a proposed solution?

Yes I commented on the commit: https://github.com/celery/django-celery-results/commit/3f74b825fc1d7af6d5dccc9a9ff583abfb0aa0ab#commitcomment-73051492

Code looks something like this:
`
        with transaction.atomic():
            # We need to know if `count` hits 0.
            # wrap the update in a transaction
            # with a `select_for_update` lock to prevent race conditions.
            # SELECT FOR UPDATE is not supported on all databases
            try:
                chord_counter = (
                    ChordCounter.objects.select_for_update()
                    .get(group_id=gid)
                )
            except ChordCounter.DoesNotExist:
                logger.warning("Can't find ChordCounter for Group %s", gid)
                return

`
