### ISSUE TITLE
Accepted Unit Testing patterns fail to store result

### ISSUE THREAD

**Issue by KeynesYouDigIt** [celery/django-celery-results#49]
Please let me know if I am missing something.

Celery tasks should generally be set to ALWAYS_EAGER for unit testing
http://docs.celeryproject.org/en/latest/userguide/testing.html?highlight=unit%20test

I've been trying this in my unit tests, and the results dont appear in the back end, just the successful task. Any recommendations on getting the task results to store properly when celery is always eager?

**Comment by rosendin** [comment]
Having this issue too and unable to call my eager task in my unit test.

Here is the full stacktrace:

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E...
======================================================================
ERROR: test_no_error (app.tests.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django_celery_results.models.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: django_celery_results_taskresult.task_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/test/utils.py", line 384, in inner
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/Users/path/to/app/server/api/tests.py", line 53, in test_no_error
    result = my_task(pk, arg1, arg2)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/Users/path/to/app/server/api/tasks.py", line 37, in my_task
    self.update_state(state='PROGRESS')
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/celery/app/task.py", line 895, in update_state
    self.backend.store_result(task_id, meta, state)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/celery/backends/base.py", line 309, in store_result
    request=request, **kwargs)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 29, in _store_result
    meta=meta,
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django_celery_results/managers.py", line 119, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 506, in _create_object_from_params
    six.reraise(*exc_info)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/path/to/code/server/venv/lib/python3.6/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/path/to/app/server/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: django_celery_results_taskresult.task_id

----------------------------------------------------------------------
Ran 4 tests in 0.387s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

This is causing two exceptions that I would like to avoid:
- django_celery_results.models.DoesNotExist: TaskResult matching query does not exist.
- sqlite3.IntegrityError: NOT NULL constraint failed: django_celery_results_taskresult.task_id

**Comment by KeynesYouDigIt** [comment]
@rosendin I ended up adding something to store the task info immediately when always eager. This is pretty ugly, do any of the maintainers of this lib know a better way?
```python
        quick_result = json.dumps(task.result) if task.status == 'SUCCESS' else None
        TaskResult.objects.create(task_id=task.task_id, status=task.status, result=quick_result)
```

**Comment by tomwojcik** [comment]
Down the rabbit hole we go!

https://github.com/celery/celery/blob/2a6c7cfe3b1283961887bf1cb3f5aa6c8aa70820/celery/app/trace.py#L323

https://github.com/celery/celery/blob/2a6c7cfe3b1283961887bf1cb3f5aa6c8aa70820/celery/app/trace.py#L338

https://github.com/celery/celery/blob/2a6c7cfe3b1283961887bf1cb3f5aa6c8aa70820/celery/app/trace.py#L476-L478

https://github.com/celery/celery/blob/2a6c7cfe3b1283961887bf1cb3f5aa6c8aa70820/celery/backends/base.py#L150-L156

https://github.com/celery/celery/blob/2a6c7cfe3b1283961887bf1cb3f5aa6c8aa70820/celery/backends/base.py#L425-L440

https://github.com/celery/django-celery-results/blob/347da9c061199a3461f677973428b456ae205cc8/django_celery_results/backends/database.py#L26-L54

If it's `eager` and you want to `store_result`, celery WON'T publish the result.

**Comment by tomwojcik** [comment]
Celery 5.1.0 has been released. Have a look at [task_store_eager_result](https://docs.celeryproject.org/en/stable/userguide/configuration.html#task-store-eager-result).

@auvipy I think it can be closed. :)
