### ISSUE TITLE
Chords not supported when using 'django-db' backend

### ISSUE THREAD

**Issue by asfaltboy** [celery/django-celery-results#52]
I'm trying a simple chord example while using the 'django-db' result backend, and get back this error:

```
Traceback (most recent call last):
  File "/Users/pavel/dev/test_proj/src/batch/tests/test_batch.py", line 51, in test_stringing
    queue_batch()
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/Users/pavel/dev/test_proj/src/batch/tasks.py", line 218, in queue_batch
    schedule_tasks(tasks, object)
  File "/Users/pavel/dev/test_proj/src/batch/tasks.py", line 196, in schedule_tasks
    chord(all_tasks_group)(set_object_state.s(object_id=object.id)).delay()
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/canvas.py", line 1196, in __call__
    return self.apply_async((), {'body': body} if body else {}, **options)
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/canvas.py", line 1237, in apply_async
    body=body, task_id=task_id, **options)
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/canvas.py", line 1251, in apply
    args=(tasks.apply(args, kwargs).get(propagate=propagate),),
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/result.py", line 635, in get
    on_message=on_message,
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/result.py", line 746, in join_native
    on_message, on_interval):
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/result.py", line 724, in iter_native
    on_message=on_message, on_interval=on_interval,
  File "/Users/pavel.virtualenvs/test_proj/lib/python3.6/site-packages/celery/backends/base.py", line 448, in iter_native
    return self.get_many(
AttributeError: 'DatabaseBackend' object has no attribute 'get_many'
```

Does anyone know if this is possible, and how can I work around this?

**Comment by auvipy** [comment]
a reproducible test and settings are required

**Comment by yellow-sky** [comment]
Now:


3.0.4
NotImplementedError
Starting chords requires a result backend to be configured.  Note that a group chained with a task is also upgraded to be a chord, as this pattern requires synchronization.  Result backends that supports chords: Redis, Database, Memcached, and mor

**Comment by AllexVeldman** [comment]
@auvipy I'm extending the `django_celery_results.backends.DatabaseBackend` with chord synchronisation from the database (replacement of the `unlock_chord` task) for a private project. would this be an interesting addition to this package?

**Comment by auvipy** [comment]
> @auvipy I'm extending the `django_celery_results.backends.DatabaseBackend` with chord synchronisation from the database (replacement of the `unlock_chord` task) for a private project. would this be an interesting addition to this package?

please feel free to open a PR :)
