### ISSUE TITLE
OperationalError: (2006, 'MySQL server has gone away') after upgrading from celery 4.1.0 to 4.2.0

### ISSUE THREAD

**Issue by mghantous** [celery/django-celery-results#58]
I'm using an amqp broker and the following packages: 
```
Django==1.11.14
django-celery-results==1.0.1
amqp==2.3.2
kombu==4.2.1
```

After upgrading from celery 4.1.0 to 4.2.0, I am getting the following error:

```bash
[2018-07-18 18:47:02,439: ERROR/ForkPoolWorker-1] Task my_app.common.tasks.echo[f8e242bf-14af-48c7-a20f-9d6d94e4cc45] raised unexpected: OperationalError(2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/srv/my_app/local/lib/python2.7/site-packages/celery/app/trace.py", line 442, in trace_task
    uuid, retval, task_request, publish_result,
  File "/srv/my_app/local/lib/python2.7/site-packages/celery/backends/base.py", line 146, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/srv/my_app/local/lib/python2.7/site-packages/celery/backends/base.py", line 322, in store_result
    request=request, **kwargs)
  File "/srv/my_app/local/lib/python2.7/site-packages/django_celery_results/backends/database.py", line 29, in _store_result
    meta=meta,
  File "/srv/my_app/local/lib/python2.7/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/srv/my_app/local/lib/python2.7/site-packages/django_celery_results/managers.py", line 119, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: (2006, 'MySQL server has gone away')
```

The strange part is the task result actually makes it to the database.

```python
In [3]: vars(TaskResult.objects.get(task_id='f8e242bf-14af-48c7-a20f-9d6d94e4cc45'))
lims.settings django.db.backends DEBUG (0.002) SELECT `django_celery_results_taskresult`.`id`, `django_celery_results_taskresult`.`task_id`, `django_celery_results_taskresult`.`status`, `django_celery_results_taskresult`.`content_type`, `django_celery_results_taskresult`.`content_encoding`, `django_celery_results_taskresult`.`result`, `django_celery_results_taskresult`.`date_done`, `django_celery_results_taskresult`.`traceback`, `django_celery_results_taskresult`.`hidden`, `django_celery_results_taskresult`.`meta` FROM `django_celery_results_taskresult` WHERE `django_celery_results_taskresult`.`task_id` = 'f8e242bf-14af-48c7-a20f-9d6d94e4cc45'; args=('f8e242bf-14af-48c7-a20f-9d6d94e4cc45',)
lims.settings django.db.backends DEBUG (0.002) SELECT `django_celery_results_taskresult`.`id`, `django_celery_results_taskresult`.`task_id`, `django_celery_results_taskresult`.`status`, `django_celery_results_taskresult`.`content_type`, `django_celery_results_taskresult`.`content_encoding`, `django_celery_results_taskresult`.`result`, `django_celery_results_taskresult`.`date_done`, `django_celery_results_taskresult`.`traceback`, `django_celery_results_taskresult`.`hidden`, `django_celery_results_taskresult`.`meta` FROM `django_celery_results_taskresult` WHERE `django_celery_results_taskresult`.`task_id` = 'f8e242bf-14af-48c7-a20f-9d6d94e4cc45'; args=('f8e242bf-14af-48c7-a20f-9d6d94e4cc45',)
Out[3]:
{'_state': <django.db.models.base.ModelState at 0x7fc6f86acfd0>,
 'content_encoding': u'utf-8',
 'content_type': u'application/json',
 'date_done': datetime.datetime(2018, 7, 18, 18, 47, 2),
 'hidden': False,
 'id': 7L,
 'meta': u'{"children": []}',
 'result': u'{"exc_message": [2006, "MySQL server has gone away"], "exc_module": "django.db.utils", "exc_type": "OperationalError"}',
 'status': u'FAILURE',
 'task_id': u'f8e242bf-14af-48c7-a20f-9d6d94e4cc45',
 'traceback': u'Traceback (most recent call last):\n  File "/srv/my_app/local/lib/python2.7/site-packages/celery/app/trace.py", line 442, in trace_task\n    uuid, retval, task_request, publish_result,\n  File "/srv/my_app/local/lib/python2.7/site-packages/celery/backends/base.py", line 146, in mark_as_done\n    self.store_result(task_id, result, state, request=request)\n  File "/srv/my_app/local/lib/python2.7/site-packages/celery/backends/base.py", line 322, in store_result\n    request=request, **kwargs)\n  File "/srv/my_app/local/lib/python2.7/site-packages/django_celery_results/backends/database.py", line 29, in _store_result\n    meta=meta,\n  File "/srv/my_app/local/lib/python2.7/site-packages/django_celery_results/managers.py", line 50, in _inner\n    return fun(*args, **kwargs)\n  File "/srv/my_app/local/lib/python2.7/site-packages/django_celery_results/managers.py", line 119, in store_result\n    obj, created = self.get_or_create(task_id=task_id, defaults=fields)\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 464, in get_or_create\n    return self.get(**lookup), False\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get\n    num = len(clone)\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__\n    self._fetch_all()\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__\n    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)\n  File "/srv/my_app/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql\n    raise original_exception\nOperationalError: (2006, \'MySQL server has gone away\')\n'}
 ```

If I switch to an rpc result backend instead of django-db, the issue goes away and the task succeeds. Is there a compatibility problem between django-celery-results==1.0.1 and celery==4.2.0?

**Comment by mghantous** [comment]
It seems to be related to this PR https://github.com/celery/celery/pull/4292
When I get rid of my `'CONN_MAX_AGE': 60` setting, it seems to resolve the issue.

Perhaps I should close the issue and report it on https://github.com/celery/ instead?

**Comment by oortega** [comment]
@mghantous  same issue with:

**#celery==4.0.2**

amqp==2.1.4
billiard==3.5.0.2
celery==4.0.2
Django==1.11.2
django-celery-beat==1.0.1
django-celery-results==1.0.1
kombu==4.0.2
MySQL-python==1.2.5
pytz==2017.2
vine==1.1.3

**After upgrade celery==4.2.1:**

amqp==2.3.2
billiard==3.5.0.4
celery==4.2.1
Django==1.11.2
django-celery-beat==1.1.1
django-celery-results==1.0.1
kombu==4.2.1
MySQL-python==1.2.5
pytz==2018.5
redis==2.10.6
vine==1.1.4

**Comment by oortega** [comment]
Hi, @mghantous apparently the problem comes from your task, this was my case.
By placing close_old_connections () within def store_result (........) I could see that my task in some parts took a long time and the connection with the database was lost, so also within my task place close_old_connections.

So modify store_result (): https://github.com/celery/django-celery-results/blob/master/django_celery_results/managers.py#L87

```
def store_result(self, content_type, content_encoding,
                 task_id, result, status,
                 traceback=None, meta=None):
    """Store the result and status of a task.
    """
    fields = {
        'status': status,
        'result': result,
        'traceback': traceback,
        'meta': meta,
        'content_encoding': content_encoding,
        'content_type': content_type,
    }
    
    #Fix temporary (2006, 'MySQL server has gone away')
    from django.db import close_old_connections
    close_old_connections()

    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
    if not created:
        for k, v in items(fields):
            setattr(obj, k, v)
        obj.save()
    return obj
```

I hope I help you, Regards

**Comment by mghantous** [comment]
Thank you for the workaround. Hopefully there is a more permanent fix. The task I have been testing doesn't do anything with the database other than have its result be stored (it simply echos a message).

**Comment by auvipy** [comment]
I hope this is fixed in celery master.
