### ISSUE TITLE
Support for revoked tasks

### ISSUE THREAD

**Issue by Noxwizard** [celery/django-celery-results#74]
Is this library supposed to be able to support task revocation? I've run into a problem where Celery flags the task as revoked, states that it's discarding it, but then attempts to run it. Additionally, since revoked tasks don't get their arguments passed along from Celery, the task is called without them and causes exceptions to occur. I've traced this back to my use of the django-celery-results library.

When a task is revoked, Celery's [`mark_as_revoked()`](https://github.com/celery/celery/blob/v4.2.1/celery/backends/base.py#L190) method makes a call to `store_result()` to store the revocation as the result, provided the task's call didn't have `ignore_result` set to True. This eventually calls into django-celery-results' [`store_result()`](https://github.com/celery/django-celery-results/blob/master/django_celery_results/managers.py#L126) which calls into Django to create an instance of (and run!) the task.

Versions:
- Celery: 4.2.1
- Django: 1.11.16
- django-celery-results: master

Broker: RabbitMQ
Result Backend: django-db

Simple reproduction code:
tasks.py:
```
from __future__ import absolute_import, unicode_literals
from django_celery.celery import app

@app.task
def add(x, y):
    return x + y

@app.task
def add_no_crash(*args, **kwargs):
    print('In add_no_crash()')

    if len(args) == 2:
        x = args[0]
        y = args[1]
        return x + y

    return None
```
The second task is simply to show that it does actually enter and run the task.

A simple task runner:
```
import django
import os
import datetime

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "django_celery.settings")
django.setup()

from celery_test.tasks import add
from celery.result import AsyncResult
from time import sleep

now = datetime.datetime.utcnow()
runat = now + datetime.timedelta(seconds=30)
print('Time is: {}'.format(now))
print('Task scheduled to run at: {}'.format(runat))
result = add.apply_async((1,2), eta=runat)
print('Task ID: {}'.format(result.task_id))
sleep(5)
print('Revoking task')
AsyncResult(result.task_id).revoke()
```

Results:
```
[2018-11-11 22:08:34,323: INFO/MainProcess] Received task: celery_test.tasks.add[7a4bf100-ca02-4e32-ab9d-a6552e9e939e]  ETA:[2018-11-11 22:09:34.290097+00:00] 
[2018-11-11 22:08:34,335: INFO/MainProcess] Tasks flagged as revoked: 7a4bf100-ca02-4e32-ab9d-a6552e9e939e
[2018-11-11 22:09:34,290: INFO/MainProcess] Discarding revoked task: celery_test.tasks.add[7a4bf100-ca02-4e32-ab9d-a6552e9e939e]
[2018-11-11 22:09:34,317: ERROR/MainProcess] Error in timer: TypeError("add() missing 2 required positional arguments: 'x' and 'y'",)
Traceback (most recent call last):
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django_celery_results.models.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 136, in fire_timers
    entry()
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 477, in apply_eta_task
    self.on_task_request(task)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/worker/request.py", line 518, in execute_using_pool
    if (self.expires or task_id in revoked_tasks) and self.revoked():
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/worker/request.py", line 280, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/worker/request.py", line 263, in _announce_revoked
    self.id, reason, request=self, store_result=self.store_errors,
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/backends/base.py", line 191, in mark_as_revoked
    traceback=None, request=request)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/backends/base.py", line 322, in store_result
    request=request, **kwargs)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django/db/models/query.py", line 499, in _create_object_from_params
    params = {k: v() if callable(v) else v for k, v in params.items()}
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/django/db/models/query.py", line 499, in <dictcomp>
    params = {k: v() if callable(v) else v for k, v in params.items()}
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/app/trace.py", line 642, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/home/noxwizard/.virtualenvs/django-celery/lib/python3.6/site-packages/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
TypeError: add() missing 2 required positional arguments: 'x' and 'y'
```

For the time being, I've written a decorator that I use on each task that will automatically check to see if the task has been revoked and then bail if required. It would be nice to not need it though.

**Comment by Noxwizard** [comment]
Applying that patch does indeed fix the problem. Thanks
