### ISSUE TITLE
NUL character in traceback with postgres DB backend causes "RuntimeWarning: Exception raised outside body"

### ISSUE THREAD

**Issue by dsalisbury** [celery/django-celery-results#82]
Hey

There's an issue I've been hitting which occurs when I'm running django-celery-results backed by a postgres database and a task raises an exception containing a NUL character; when storing the result a ValueError comes out causing the result to never actually be saved to the DB. From my testing, this doesn't occur if I return a string with a NUL in it, only if I raise an exception.

I've recreated this in a dummy project with minimal things, so I know it's not something with my actual app where I found this.

Here's the celery.py file created by following the first steps with django guide, which contains a task that will either return a string with a NUL character, or raise an exception with one:

```python
from __future__ import absolute_import, unicode_literals
import os
from celery import Celery

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'faily.settings')

app = Celery('faily')

# Using a string here means the worker doesn't have to serialize
# the configuration object to child processes.
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
app.config_from_object('django.conf:settings', namespace='CELERY')

# Load task modules from all registered Django app configs.
app.autodiscover_tasks()


@app.task
def nully(fail=False):
    n = '---\x00+++'
    if fail:
        raise Exception(n)
    return n

```

And here's the worker output from running the task first with fail=False, then secondly with fail=True:

```
$ pipenv run celery -A faily.celery worker
2018-12-14 03:43:30,036: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2018-12-14 03:43:30,040: DEBUG/MainProcess] | Worker: Building graph...
[2018-12-14 03:43:30,040: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, Beat, StateDB, Consumer}
[2018-12-14 03:43:30,055: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2018-12-14 03:43:30,055: DEBUG/MainProcess] | Consumer: Building graph...
[2018-12-14 03:43:30,071: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Gossip, Heart, Tasks, Control, event loop}

 -------------- celery@C02WW2AAHV2T v4.2.1 (windowlicker)
---- **** -----
--- * ***  * -- Darwin-18.2.0-x86_64-i386-64bit 2018-12-14 03:43:30
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         faily:0x10c2e92b0
- ** ---------- .> transport:   redis://localhost:6379/1
- ** ---------- .> results:
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . faily.celery.nully

[2018-12-14 03:43:30,092: DEBUG/MainProcess] | Worker: Starting Hub
[2018-12-14 03:43:30,092: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:30,092: DEBUG/MainProcess] | Worker: Starting Pool
[2018-12-14 03:43:30,256: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:30,257: DEBUG/MainProcess] | Worker: Starting Consumer
[2018-12-14 03:43:30,257: DEBUG/MainProcess] | Consumer: Starting Connection
[2018-12-14 03:43:30,290: INFO/MainProcess] Connected to redis://localhost:6379/1
[2018-12-14 03:43:30,290: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:30,291: DEBUG/MainProcess] | Consumer: Starting Events
[2018-12-14 03:43:30,307: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:30,307: DEBUG/MainProcess] | Consumer: Starting Mingle
[2018-12-14 03:43:30,307: INFO/MainProcess] mingle: searching for neighbors
[2018-12-14 03:43:31,346: INFO/MainProcess] mingle: all alone
[2018-12-14 03:43:31,346: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:31,346: DEBUG/MainProcess] | Consumer: Starting Gossip
[2018-12-14 03:43:31,363: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:31,363: DEBUG/MainProcess] | Consumer: Starting Heart
[2018-12-14 03:43:31,367: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:31,368: DEBUG/MainProcess] | Consumer: Starting Tasks
[2018-12-14 03:43:31,374: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:31,374: DEBUG/MainProcess] | Consumer: Starting Control
[2018-12-14 03:43:31,385: DEBUG/MainProcess] ^-- substep ok
[2018-12-14 03:43:31,386: DEBUG/MainProcess] | Consumer: Starting event loop
[2018-12-14 03:43:31,386: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2018-12-14 03:43:31,388: WARNING/MainProcess] /Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2018-12-14 03:43:31,389: INFO/MainProcess] celery@C02WW2AAHV2T ready.
[2018-12-14 03:43:31,389: DEBUG/MainProcess] basic.qos: prefetch_count->16


#######
# fail=False

[2018-12-14 03:43:37,433: INFO/MainProcess] Received task: faily.celery.nully[9df5449c-d293-4d59-b1d3-db9c66aaf858]
[2018-12-14 03:43:37,434: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10c386510> (args:('faily.celery.nully', '9df5449c-d293-4d59-b1d3-db9c66aaf858', {'lang': 'py', 'task': 'faily.celery.nully', 'id': '9df5449c-d293-4d59-b1d3-db9c66aaf858', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '9df5449c-d293-4d59-b1d3-db9c66aaf858', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'fail': False}", 'origin': 'gen73465@C02WW2AAHV2T', 'reply_to': 'f94d1485-8c49-374a-9005-27a2ba1a4da6', 'correlation_id': '9df5449c-d293-4d59-b1d3-db9c66aaf858', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[], {"fail": false}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-12-14 03:43:37,436: DEBUG/MainProcess] Task accepted: faily.celery.nully[9df5449c-d293-4d59-b1d3-db9c66aaf858] pid:73501
[2018-12-14 03:43:37,470: INFO/ForkPoolWorker-2] Task faily.celery.nully[9df5449c-d293-4d59-b1d3-db9c66aaf858] succeeded in 0.032973800999998915s: '---+++'



#######
# fail=True, so the exception will be raised

[2018-12-14 03:43:42,632: INFO/MainProcess] Received task: faily.celery.nully[114f8402-d62e-40e2-b4d7-b522b85ce91f]
[2018-12-14 03:43:42,633: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10c386510> (args:('faily.celery.nully', '114f8402-d62e-40e2-b4d7-b522b85ce91f', {'lang': 'py', 'task': 'faily.celery.nully', 'id': '114f8402-d62e-40e2-b4d7-b522b85ce91f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '114f8402-d62e-40e2-b4d7-b522b85ce91f', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': "{'fail': True}", 'origin': 'gen73465@C02WW2AAHV2T', 'reply_to': 'f94d1485-8c49-374a-9005-27a2ba1a4da6', 'correlation_id': '114f8402-d62e-40e2-b4d7-b522b85ce91f', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'[[], {"fail": true}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-12-14 03:43:42,635: DEBUG/MainProcess] Task accepted: faily.celery.nully[114f8402-d62e-40e2-b4d7-b522b85ce91f] pid:73500
[2018-12-14 03:43:42,681: WARNING/ForkPoolWorker-1] /Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py:561: RuntimeWarning: Exception raised outside body: ValueError('A string literal cannot contain NUL (0x00) characters.'):
Traceback (most recent call last):
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/dsalisbury/src/scratch/nul_fail/faily/celery.py", line 24, in nully
    raise Exception(n)
Exception: ---+++

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py", line 396, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py", line 338, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py", line 172, in handle_error_state
    call_errbacks=call_errbacks)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/app/trace.py", line 217, in handle_failure
    call_errbacks=call_errbacks,
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/backends/base.py", line 157, in mark_as_failure
    traceback=traceback, request=request)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/backends/base.py", line 322, in store_result
    request=request, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 488, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 522, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
ValueError: A string literal cannot contain NUL (0x00) characters.

  exc, exc_info.traceback)))
[2018-12-14 03:43:42,755: ERROR/MainProcess] Pool callback raised exception: ValueError('A string literal cannot contain NUL (0x00) characters.')
Traceback (most recent call last):
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/billiard/pool.py", line 1747, in safe_apply_callback
    fun(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/worker/request.py", line 367, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/backends/base.py", line 157, in mark_as_failure
    traceback=traceback, request=request)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/celery/backends/base.py", line 322, in store_result
    request=request, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 488, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 522, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/dsalisbury/.virtualenvs/nul_fail-M69eqECC/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
ValueError: A string literal cannot contain NUL (0x00) characters.
```

**Comment by auvipy** [comment]
were you able to fix this ValueError: A string literal cannot contain NUL (0x00) characters. error?

**Comment by auvipy** [comment]
not a bug rather user code IMHO
